---
# tasks file for fedora_dnf_local_plugin

# install dnf local plugin and createrepo_c
- name: Install DNF local plugin
  ansible.builtin.package:
    name: "{{ dlp_packages }}"
    state: present

# Backup configuration file and set enabled attribute
- name: Set enabled in conf and backup
  community.general.ini_file:
    path: "{{ dlp_conf }}"
    backup: true
    section: main
    option: enabled
    value: "{{ dlp_enabled }}"

# set repodir
- name: Set repodir in conf
  community.general.ini_file:
    path: "{{ dlp_conf }}"
    section: main
    option: repodir
    value: "{{ dlp_repodir }}"

# set createrepo enabled
- name: Set createrepo boolean in conf
  community.general.ini_file:
    path: "{{ dlp_conf }}"
    section: createrepo
    option: enabled
    value: "{{ dlp_createrepo_enabled }}"

# set cachedir if defined
- name: Set cachedir if defined
  community.general.ini.file:
    path: "{{ dlp_conf }}"
    section: createrepo
    option: cachedir
    value: "{{ dlp_cachedir }}"
  when: dlp_cachedir is directory

# check for presence of systemctl
# may not exist on container for example
- name: systemctl check
  stat:
    path: /usr/bin/systemctl
  register: _statresult

# message if no systemctl
- name: systemctl message
  debug:
    msg: "{{ _statresult.stat.exists | ternary('systemctl found','no systemctl - skipping') }}"

# call systemctl daemon reload to update dnf configuration
- name: Systemctl reload for dnf
  ansible.builtin.systemd:
    daemon_reload: true
  when: _statresult.stat.exists
...
